FROM node:22.15.0-bookworm-slim

WORKDIR /app

RUN apt-get update -y && \
    apt-get install -y python3 build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev:docker"]