services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ticket-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_DB_USER}:${POSTGRES_DB_PASSWORD}@ticket-db-dev:5432/${POSTGRES_DB_NAME}
    env_file:
      - .env
    depends_on:
      - db-dev
    restart: unless-stopped

  db-dev:
    image: postgres:17.4
    container_name: ticket-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: